name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Download stats card
        run: |
          for i in {1..5}; do
            curl -f -o profile/stats.svg "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=tokyo_night" && break || sleep 10
          done

      - name: Download top languages card
        run: |
          sleep 5
          for i in {1..5}; do
            curl -f -o profile/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=${{ github.repository_owner }}&layout=compact&theme=tokyo_night" && break || sleep 10
          done

      - name: Download pin card
        run: |
          sleep 5
          for i in {1..5}; do
            curl -f -o profile/pin-readme-tools-github-readme-stats.svg "https://github-readme-stats.vercel.app/api/pin?username=readme-tools&repo=github-readme-stats&theme=tokyo_night" && break || sleep 10
          done

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push